# Generated by Django 5.0.6 on 2024-07-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ves', models.FloatField(default=3.8)),
                ('dlina_setki', models.FloatField(default=1500)),
                ('untill', models.CharField(default='cm', max_length=10)),
                ('razmer_sechenya', models.FloatField(default=3.6)),
                ('unitrs', models.CharField(default='mm', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
